# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

version: '3'
services:
  bridge:
    platform: linux/x86_64
    build:
      context: .
    container_name: bridge
    environment:
      - KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD
    command: --config /bridgeConfig/config.json --verbosity trace --blockstore /blockstore
    volumes:
      - ./bridgeConfig:/bridgeConfig
      - ./keys:/keys/
      - ./blockstore:/blockstore
    network_mode: host
